### ISSUE TITLE
warning: array subscript has type 'char' during compilation

### ISSUE THREAD

**Issue by szaydel** [Seagate/opensea-operations#5]
Good morning. I am observing the following warning, and it seems to be a result of using a signed integer as an index.
```
[61/113] Compiling C object subprojects/opensea-operations/libopensea-operations.a.p/src_smart.c.o
../subprojects/opensea-operations/src/smart.c: In function 'print_ATA_SMART_Attribute_Raw_Int_Value':
../subprojects/opensea-operations/src/smart.c:1393:57: warning: array subscript has type 'char' [-Wchar-subscripts]
 1393 |         snprintf(temp, 4, "%02"PRIX8"", rawdataParameter[rawIter]);
      |                                                         ^
```
Looking at this a bit, it seems like a bad idea to use `finalIndex`, which could be less than zero as `rawIter`, which ultimately would allow for data outside of the array to be accessed. This should all be unsigned in my view, even if it feels like the risk here is minimal. Arguably, if we have to have this signed indexing here, we should at least make sure that the value of `finalIndex` is non-negative.
```
static void print_ATA_SMART_Attribute_Raw_Int_Value(uint8_t* rawdataParameter, int intialIndex, char finalIndex)
{
    int8_t rawIter;
    char rawdata[20] = { 0 };
    char temp[4];
    uint32_t  rawdataIntValue = 0;
    for (rawIter = finalIndex; rawIter >= intialIndex; rawIter--)
    {
        snprintf(temp, 4, "%02"PRIX8"", rawdataParameter[rawIter]);
        common_String_Concat(rawdata, 20, temp);
    }
    rawdataIntValue = hex2int(rawdata);
    printf("%" PRIu32, rawdataIntValue);
    //sscanf(rawdata, "%x", &rawdataIntValue);
    //printf("%X", rawdataIntValue);
    return;
}
```

**Comment by vonericsen** [comment]
I have pushed a couple changes to the release/Release-22.03 branches for the moment that will resolve this issue.
I have not merged your recent pull request to fix meson.build to this branch yet and need to do that, but this should resolve this warning.
We can close this once I have merged it to develop too.

**Comment by szaydel** [comment]
That sounds good, @vonericsen!  Thanks for a quick response.

**Comment by vonericsen** [comment]
This has been merged to develop now. If you no longer see this warning show up, we can close this.

**Comment by szaydel** [comment]
Sounds good, thanks. I will have a look when I have a bit of time.
